test:
  name: Solidity Transfer
  description: This is a solidity transfer benchmark of FISCO BCOS for caliper
  workers:
    number: 4
  rounds:
    - label: addUser
      description: generate users for transfer test later
      txNumber:
        - 1000
      rateControl:
        - type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: benchmarks/samples/fisco-bcos/transfer/solidity/addUser.js
    - label: transfer
      description: transfer money between users
      txNumber:
        - 10000
      rateControl:
        - type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: benchmarks/samples/fisco-bcos/transfer/solidity/transfer.js
        arguments:
          txnPerBatch: 10
